DROP DATABASE IF EXISTS AgoraTrading;
CREATE DATABASE AgoraTrading;
USE AgoraTrading;

CREATE TABLE Business (
businessID INT AUTO_INCREMENT PRIMARY KEY,
businessName VARCHAR(70) NOT NULL,
registrationNumber VARCHAR(15) NOT NULL, 
bankNumber VARBINARY(500) NOT NULL,
contactNumber VARCHAR(15) NOT NULL,
email VARCHAR(60) NOT NULL,
logo LONGBLOB NULL,
hqAddress VARCHAR(50) NOT NULL,
hqCity VARCHAR(50) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE AgoraUser (
userID INT AUTO_INCREMENT PRIMARY KEY,
firstName VARCHAR(50) NOT NULL,
lastName VARCHAR(50) NOT NULL,
email VARCHAR(60) NULL,
username VARCHAR(50) NOT NULL,
userPassword VARBINARY(500) NOT NULL,
address VARCHAR(50) NULL,
city VARCHAR(50) NULL,
contactNumber VARCHAR(15) NULL,
userRole VARCHAR(20) NOT NULL,
businessID INT NULL,
FOREIGN KEY (businessID) REFERENCES Business(businessID)
)ENGINE=InnoDB;

CREATE TABLE ItemCategory (
categoryID INT AUTO_INCREMENT PRIMARY KEY,
category VARCHAR(50) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE Item (
itemID INT AUTO_INCREMENT PRIMARY KEY,
itemName VARCHAR(70) NOT NULL,
itemDescription TEXT NOT NULL,
photo LONGBLOB NULL,
price DECIMAL(10,2) NOT NULL,
inStock INT NOT NULL,
sellerID INT NOT NULL,
categoryID INT NOT NULL,
FOREIGN KEY (sellerID) REFERENCES AgoraUser(userID),
FOREIGN KEY (categoryID) REFERENCES ItemCategory(categoryID)
)ENGINE=InnoDB;

CREATE TABLE Purchase (
purchaseID INT AUTO_INCREMENT PRIMARY KEY,
purchaseDate DATETIME NOT NULL,
buyerID INT NOT NULL,
FOREIGN KEY (buyerID) REFERENCES AgoraUser(userID)
)ENGINE=InnoDB;

CREATE TABLE OrderLine (
orderlineID INT AUTO_INCREMENT PRIMARY KEY,
quantity INT NOT NULL,
price DECIMAL(10,2) NOT NULL,
itemID INT NOT NULL,
purchaseID INT NOT NULL,
FOREIGN KEY (itemID) REFERENCES Item(itemID),
FOREIGN KEY (purchaseID) REFERENCES Purchase(purchaseID)
)ENGINE=InnoDB;

